version: '3.8'
services:
  api:
    build:
      context: ./docker/nginx-prod
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    ports:
      - '8082:80'
    deploy:
      resources:
        limits:
          cpus: '1.8'
          memory: '3g'
        reservations:
          cpus: '0.2'
          memory: '512m'
  database:
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
        reservations:
          cpus: '0.5'
          memory: '512m'
  redis:
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
  elastic1:
    ports:
      - '9200:9200'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2g'
        reservations:
          cpus: '0.5'
          memory: '512m'
  elastic2:
    ports:
      - '9201:9200'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2g'
        reservations:
          cpus: '0.2'
          memory: '512m'

