<?php

namespace Database\Seeders;

use App\Models\OfTag;
use App\Models\OfTagsGroup;
use Illuminate\Database\Seeder;

class BindOfTagsWithGroupsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tags = OfTag::all();
        $groups = OfTagsGroup::all();
        $categoryGroups = $this->getCagegoryGroupArray();

        foreach ($categoryGroups as $groupKey => $categories) {
            $group = $groups->where('key', $groupKey)->first();
            $tags->filter(function ($tag) use ($categories) {
                return in_array($tag->name, $categories);
            })->each(function ($tag) use ($group) {
                $tag->groups()->attach($group);
            });
        }

        $tags->where('results', '>=', 10000)->each(function ($tag) use ($groups) {
            $group = $groups->where('key', '=','most_populated')->first();
            $tag->groups()->attach($group);
        });

        $tags->where('traffic', '>', 500)->each(function ($tag) use ($groups) {
            $group = $groups->where('key', '=','top')->first();
            $tag->groups()->attach($group);
        });
    }

    public function getCagegoryGroupArray()
    {
        return [
            'other' =>
                [
                    '10 No Ppv',
                    'A Unrated',
                    'Ahegao',
                    'Almeida',
                    'Artigs Education',
                    'Asianfeet',
                    'Avocado',
                    'Barelylegal',
                    'Baylor',
                    'Big 420',
                    'Bimbo',
                    'Boots',
                    'Braces Fetish',
                    'Bwc',
                    'Camgirls',
                    'Candid',
                    'Candids',
                    'Cardo',
                    'Carrot Cake',
                    'Catgirls',
                    'Cd',
                    'Chaturbate',
                    'Cheekies N Skeet',
                    'Collaborations',
                    'Collabs Meetups',
                    'Contortion',
                    'Creamy',
                    'Crossdresser',
                    'Crossfit',
                    'Cum',
                    'Cum Sluts',
                    'Cute Freak',
                    'Dad Bod 93',
                    'Deletable Purple 2',
                    'Dirty',
                    'Disorder',
                    'Dm For Custom Video',
                    'Dmv',
                    'Doll',
                    'Down There',
                    'Dysmorphia',
                    'Ebonyfeet',
                    'Erotic',
                    'Fansly',
                    'Favorita',
                    'Feedee',
                    'Fembot',
                    'Follow',
                    'Fox Forest',
                    'Freaky N Fun',
                    'From Heaven',
                    'Ga Peach',
                    'Gainer',
                    'Gauge',
                    'Giantess',
                    'Girth Quakez',
                    'Goddess',
                    'Goth',
                    'Hentai',
                    'Hijab',
                    'Hijabi',
                    'Homemade',
                    'Homies',
                    'Hooters',
                    'Hung',
                    'In The Country And Free',
                    'In Your Eyes',
                    'In Your Filthy Fantasies',
                    'Index',
                    'Inflated',
                    'Kawaii',
                    'Kawaii Samaa',
                    'Kay Love Fantasyfree',
                    'Keepers',
                    'Kim Possible',
                    'Kinkiest',
                    'Knockers',
                    'Ladyboy',
                    'Latex',
                    'Legging',
                    'Local',
                    'Marine',
                    'Massage',
                    'Middle',
                    'Military',
                    'Milking',
                    'Modelos',
                    'Nature',
                    'Naughty',
                    'Nerdy',
                    'Nerdygirl',
                    'Nerverland',
                    'New B G Content Dropping',
                    'No Ppv',
                    'Noppv',
                    'Nude',
                    'Nymph',
                    'O Booty',
                    'Of Blue',
                    'Off Grid',
                    'Olive Garden Rat',
                    'Onlyfeet',
                    'Onlyfeets',
                    'Panties',
                    'Panty',
                    'Pantyhose',
                    'Peachy Fans',
                    'Polka',
                    'Remember',
                    'Seancody',
                    'Shreds',
                    'Silicone Babe',
                    'Silky Skins',
                    'Silverfox',
                    'Simp City',
                    'Sizequeen',
                    'Sloppy',
                    'Slutty',
                    'Smoking',
                    'Sneaky',
                    'Sorry Mom',
                    'Splash Mountain',
                    'Starwars',
                    'Stockings',
                    'Stripchat',
                    'Sunflower',
                    'Swagger',
                    'Sweet Feet4U',
                    'That Foreign',
                    'The Boobs Realm',
                    'The Goddess Clue Free',
                    'Tittytuesday',
                    'Twin Peaks',
                    'Unashamed',
                    'Vip',
                    'Virgin',
                    'Waifu',
                    'Wheelchair',
                    'Where The Fun Is',
                    'Witch',
                    'Witching',
                    'Xl Executive',
                ],
            'age' =>
                [
                    '18 Year Old',
                    'Cougar',
                    'Cougars',
                    'Grandma',
                    'Granny',
                    'Teen',
                ],
            'scenario' =>
                [
                    '2 Miles From Your Position',
                    '5 Miles Away',
                    'All Over The Map',
                    'Amateur',
                    'Atlantis',
                    'Babysitter Jule',
                    'Barista',
                    'Bat Cave',
                    'Bathtub',
                    'Behind The Sun',
                    'Booty And The Beast',
                    'Brothers',
                    'Bunnyland',
                    'Carnal Captures',
                    'Casal',
                    'Cheating Hotwife Onlyfan',
                    'Cheeky Nurse',
                    'Cheerleader',
                    'College',
                    'Cosplay',
                    'Cosplay Onlyfans',
                    'Country Girl Wild',
                    'Couple 3',
                    'Cowgirl',
                    'Cuckold',
                    'Cuckoldress',
                    'Cuckquean',
                    'Daddy',
                    'Degradedsub Lexie',
                    'Dick Rating',
                    'Dick Ratingdeals',
                    'Fairy',
                    'Farm',
                    'Farmgirl',
                    'Femboy',
                    'Fsu',
                    'Ftm Femboy',
                    'Girl Next Door',
                    'Gloryhole',
                    'Gym',
                    'Gym Princess',
                    'Hotwife',
                    'Hotwife Nextdoor',
                    'Housewife',
                    'Kinky Husband Wife',
                    'Maledom',
                    'Mistress',
                    'Mom Daughter',
                    'Mom Free',
                    'Mommy',
                    'Mother Daughter',
                    'Nasty Girls',
                    'No Face Couple',
                    'Noface Housewife',
                    'Nurse',
                    'Onlyfans Creampie',
                    'Outside',
                    'Pegging',
                    'Perv Mom',
                    'Playhouse',
                    'Prison',
                    'Searching For Boyfriend',
                    'Sextape',
                    'Sexting',
                    'Sissy And Mistress',
                    'Sissy Pussy',
                    'Sisters',
                    'Stacys Mom',
                    'Stepdaughter',
                    'Stepsister',
                    'Stripper',
                    'Submissive',
                    'Swallowing Your Cum',
                    'Swinger',
                    'Swingers',
                    'Taboo',
                    'Taboo Mom Bro Sis',
                    'The Trap',
                    'The Wrong Side Of Heaven',
                    'Therapy',
                    'Twins',
                    'Twins Sisters',
                    'Upskirt',
                    'Van Life',
                    'Vore Acious Clips',
                    'Voyeur',
                    'Wedgie',
                    'Workout',
                    'Your Best Girlfriend',
                    'Your Brat',
                    'Your Dream',
                    'Your Favorite Secret',
                    'Your Hand',
                    'Your Thick Girlfriend',
                    'Yourstep Mom',
                ],
            'performer' =>
                [
                    'A Clare',
                    'A Joy',
                    'A Riannamaria',
                    'Aaliyah',
                    'Adriana',
                    'Adrianna',
                    'Ainsley',
                    'Aki Kitty',
                    'Alanna',
                    'Ale Jnilu1227',
                    'Alex Joy',
                    'Alexa',
                    'Alexxx',
                    'Alexxxis',
                    'Alice Hannah',
                    'Alice Ivy',
                    'Alina',
                    'Alipaolinetti',
                    'Aliya Ivy',
                    'Aliya Kiss',
                    'Aliyah',
                    'Ally Mae',
                    'Alwayss Ana',
                    'Aly Simmons',
                    'Alysia',
                    'Alyssa',
                    'Amalia',
                    'Amalia Garcia',
                    'Amanda Marie',
                    'Amazing Sexy Kay',
                    'Amb Jess',
                    'Amber',
                    'Amber Nicole',
                    'Amberlynn',
                    'Amberolsen 21',
                    'Ambi Bambi',
                    'Amelia',
                    'Amelia Wet Angel',
                    'Amethyst',
                    'Amina',
                    'Amira Assia',
                    'Amy Miriam',
                    'Ana',
                    'Ana Rose',
                    'Ana Tennis',
                    'Anais',
                    'Anastasia',
                    'Andrea',
                    'Angelina',
                    'Angelina Lee',
                    'Anika',
                    'Anika Skye',
                    'Ann R',
                    'Anna Bella',
                    'Anna Luu',
                    'Anna Ruka',
                    'Anna Spase',
                    'Annalisa',
                    'Annalise',
                    'Annamarie',
                    'Annelise',
                    'Annemarie',
                    'Annika',
                    'Anthony',
                    'Antonella',
                    'Antonia Freda',
                    'April Rose',
                    'Ariana Valentina',
                    'Ariane',
                    'Arianna',
                    'Ariel You Want',
                    'Aries Brat',
                    'Ariya Ray',
                    'Artemis',
                    'Ash',
                    'Ashley',
                    'Ashley Brooke',
                    'Ashley Katelyn',
                    'Ashley Marie',
                    'Ashley Marie Model',
                    'Ashley Nicole',
                    'Ashley Rae',
                    'Ashley Rose',
                    'Ashleymarie',
                    'Ashlyn',
                    'Ashton',
                    'Aspen Rain',
                    'At Rachel',
                    'Athena',
                    'Athena Rayne',
                    'Aurora',
                    'Autumn',
                    'Autumn Kait',
                    'Ava',
                    'Ava Grace',
                    'Ava Graceee',
                    'Avery Leigh',
                    'B Kiara',
                    'B Moniquee',
                    'Baby Cin',
                    'Babydoll 22',
                    'Babyface',
                    'Babyjay 00',
                    'Bad Bella',
                    'Bad Bunny',
                    'Bad Kitty',
                    'Baddie',
                    'Bailey',
                    'Bailey Madison',
                    'Bambi Ambi',
                    'Bambi Lexy',
                    'Bambi Skye',
                    'Barbiee V1',
                    'Bbygirl Mari',
                    'Beanz',
                    'Bearded Bear',
                    'Beautiful Angel',
                    'Beba Ivy',
                    'Becca',
                    'Becky Wood',
                    'Belinda',
                    'Bella Wilson',
                    'Bellababy',
                    'Bellafox Tv',
                    'Bellerose',
                    'Bianca Banks',
                    'Bibi Cherri',
                    'Blair Jade',
                    'Blonde Baby1',
                    'Blonde Barbie',
                    'Blondebarbie',
                    'Blondebombshell',
                    'Blueface Jp',
                    'Bo Pp',
                    'Boliviana Mimi',
                    'Booty Barbie',
                    'Brandi',
                    'Bratty Painkiller',
                    'Bratty Sofia',
                    'Brea Aa',
                    'Brenda',
                    'Brianna',
                    'Bridget',
                    'Brit Brat',
                    'Britt',
                    'Brittany',
                    'Brock Cok',
                    'Brye Xo',
                    'Brynn Lewis',
                    'Bunny Rose',
                    'Buttercup',
                    'Bxby Anna',
                    'C Crow',
                    'Caitlin',
                    'Caitlyn',
                    'Caleb',
                    'Calista',
                    'Calista Melissa',
                    'Callie',
                    'Callie Rose',
                    'Camille',
                    'Candy',
                    'Candy Love',
                    'Caressaxo Free',
                    'Carissa',
                    'Carl Laa',
                    'Carla K',
                    'Carlita',
                    'Carly Jane',
                    'Casey',
                    'Cassidy',
                    'Cassiopeia',
                    'Caterina Rx',
                    'Catrina',
                    'Celestial Sunflower',
                    'Celine',
                    'Chanel',
                    'Chanel Brooke',
                    'Chanel Brooks',
                    'Chantel',
                    'Chanxoxo Free',
                    'Charity',
                    'Charlotte Melai',
                    'Chastity',
                    'Cheekie',
                    'Chelle Smith',
                    'Chelsea Leigh',
                    'Chelsey',
                    'Cherry Babe',
                    'Cherry On Top99',
                    'Cherrybomb',
                    'Cheyenne Xoxo',
                    'Cheyenne Xoxofree',
                    'Chloe',
                    'Chloe Ayling',
                    'Christen Rene',
                    'Christina',
                    'Chyna Doll',
                    'Clara Walker',
                    'Clare A',
                    'Clarissa',
                    'Clarita',
                    'Claudia',
                    'Claudine',
                    'Clementine Xox',
                    'Coryn X',
                    'Courtney Foxx',
                    'Cruella',
                    'Cubby Bear',
                    'Cutie Claire',
                    'Cutipiemom Ashlee',
                    'D Lo415',
                    'Daisy Drew',
                    'Daisy Girl 13',
                    'Dalia Demirel',
                    'Dana',
                    'Dana Adult Model',
                    'Dana Rose',
                    'Dani Cake S',
                    'Dayana',
                    'Dea',
                    'Della',
                    'Deshay',
                    'Desiree',
                    'Destiny',
                    'Destiny Rose',
                    'Desus Dom',
                    'Devon',
                    'Diosaera Zeus',
                    'Dollface 666',
                    'Donna',
                    'Eden May',
                    'Ela M1111',
                    'Ela Miranda',
                    'Elaine Dvs',
                    'Eliz',
                    'Elizabeth',
                    'Elizabeth Raee',
                    'Ella Belle',
                    'Ella Enchanted',
                    'Ella Rose',
                    'Ellebelle',
                    'Ellie',
                    'Ellie Jelly',
                    'Ellie May',
                    'Elora Dior',
                    'Emily Babe',
                    'Emily Cute',
                    'Emily Rose',
                    'Emma Leigh',
                    'Emma Louise',
                    'Emma Lvx',
                    'Emmaleigh',
                    'Empress Lexx',
                    'Emy Luv',
                    'Erin Alycia',
                    'Eva Evergreene',
                    'Eve',
                    'Eve 222',
                    'Evelyn Malee',
                    'Evesss 408',
                    'Faith',
                    'Farah',
                    'Faye',
                    'Fiery Ginger',
                    'Fik Shun',
                    'Free Ash Marie',
                    'Free Mariabonita',
                    'Gabriela Bianca',
                    'Gazelle',
                    'Gemma',
                    'Genesis',
                    'Genevieve',
                    'Gfe Alice',
                    'Gfe Sophie',
                    'Gianna',
                    'Gigi Elle',
                    'Ginger Ed',
                    'Gingersnap',
                    'Goddess Mandy',
                    'Goldie Watt',
                    'Grace',
                    'Gypsyrose 805',
                    'Hail Lydia',
                    'Hailey',
                    'Hailey Chew',
                    'Hails Xoxo',
                    'Halsey',
                    'Handstand Goddess',
                    'Hannah',
                    'Hannah G',
                    'Harmony',
                    'Haylee',
                    'Heather',
                    'Heidi',
                    'Helen Ivy',
                    'Hijabhunny Srs',
                    'Hinata',
                    'Hokulani San',
                    'Holly',
                    'Honey',
                    'Honey Babyximages',
                    'Honey Bb',
                    'Honey Bunny',
                    'Honey Lexixxx',
                    'Honeyd',
                    'Hotwife Kate',
                    'I Natalia',
                    'Iam Medusa',
                    'Iam Pandoraaa',
                    'Icarley6 9',
                    'Ig Babygirlhazel',
                    'Ig Bb Zeta Twitter Zeta Bb',
                    'Im Amelia',
                    'Imogen',
                    'Inga Today',
                    'Ink Heart',
                    'Isabela Ramirez',
                    'Isabelle',
                    'Ishtar',
                    'Isla Moon',
                    'Isla Moonfree',
                    'Issa Reed',
                    'Its Amyrose',
                    'Itss Mwah',
                    'Ivy',
                    'Izzy',
                    'J Phattie',
                    'Jackie Ohh',
                    'Jade Evans',
                    'Jaelynn',
                    'Jaki Senpai',
                    'Jam Me',
                    'Jamie Lee',
                    'Janice',
                    'Jasmine Rose',
                    'Jasmine Tea',
                    'Jayden',
                    'Jazmine',
                    'Jenessagarza 69',
                    'Jenifer Caselles',
                    'Jenna',
                    'Jenni Neidhart',
                    'Jennifer',
                    'Jenny',
                    'Jess Kay',
                    'Jess Lee',
                    'Jessa Hill',
                    'Jessi Luv',
                    'Jessica',
                    'Jessica Jones',
                    'Jessica Lynn8',
                    'Jessie',
                    'Jillian',
                    'Joanna Offiziell',
                    'Jocelyn',
                    'Jodie Bell',
                    'Juicy Jayna',
                    'Juicy Justine',
                    'Juicy Lucie',
                    'Juiicy A',
                    'Julia',
                    'Julia 502',
                    'Julia Taylor',
                    'Julissa',
                    'June Summers',
                    'Just Peachyyy',
                    'Justpeachy 100',
                    'K Girl',
                    'Kadedavis Elite',
                    'Kaelyn',
                    'Kailey',
                    'Kaitlynn',
                    'Kaiyana Moon',
                    'Kali',
                    'Karina',
                    'Karla',
                    'Karlee',
                    'Karlee Steel',
                    'Kasey Kay',
                    'Kassandra',
                    'Kate',
                    'Katherinne',
                    'Kathy',
                    'Katia',
                    'Katie Daily',
                    'Katie Nurse',
                    'Katie Wild03',
                    'Katiebug',
                    'Katiie',
                    'Katrina',
                    'Katykat',
                    'Kaylamarie',
                    'Kaylee',
                    'Kaylin',
                    'Kaylynn',
                    'Kbass2 0',
                    'Kellie Mimi',
                    'Kelly Brook',
                    'Kels',
                    'Kenna',
                    'Kenzie',
                    'Kenzo K',
                    'Kiana',
                    'Kianna',
                    'Kierra',
                    'Kiki 4 2 0',
                    'Kimberlee',
                    'Kimberly',
                    'Kimmie Haze',
                    'Kimmy',
                    'Kindly',
                    'Kinky Pup 12',
                    'Kira Liv',
                    'Kirk E Wood',
                    'Kit Kit',
                    'Kitkat',
                    'Kitty',
                    'Kittybaby',
                    'Kittyboo',
                    'Kittyk',
                    'Kittykat 2020',
                    'Krista',
                    'Kristen',
                    'Krystal Price',
                    'Ksenia',
                    'Kt So',
                    'Kuromi',
                    'Lacey Baker',
                    'Lacey Rae',
                    'Lala Marie',
                    'Lapatrona',
                    'Lapetite',
                    'Latinooxl 2',
                    'Laurie',
                    'Laylaa Bby',
                    'Lea Lane',
                    'Lea Lee',
                    'Leanne',
                    'Leila',
                    'Leilani',
                    'Leilani Lotus',
                    'Lena',
                    'Lex Jayne',
                    'Lexi Lynn',
                    'Lexi Rae',
                    'Lexi Smith',
                    'Lexxxi',
                    'Lexy Xx',
                    'Leyla Lia',
                    'Libby',
                    'Lil Braids',
                    'Lil Sn00P',
                    'Lilli Vanilli',
                    'Lillie',
                    'Lilly Licksu',
                    'Lilly White1',
                    'Lils Effy',
                    'Lily',
                    'Lily Wilson',
                    'Lindsay',
                    'Lindsey',
                    'Linnea',
                    'Linny',
                    'Lisa Marie',
                    'Lisa Marieimages',
                    'Little Red Ivy',
                    'Littlered',
                    'Liv A Little',
                    'Lola',
                    'Lola Mckenzie',
                    'Lola Moon',
                    'Lola Sophie25',
                    'Lolab',
                    'Lolabunny',
                    'Lorelei',
                    'Loulou Belle',
                    'Loveless',
                    'Lovely Lila',
                    'Lovely Mimi',
                    'Lovely Nova',
                    'Loving Selena',
                    'Low Keydeadinside',
                    'Lucia Lopez98',
                    'Lucylou',
                    'Lucyspades Censored',
                    'Luisa',
                    'Luke Londonxxx',
                    'Luna Rexx',
                    'Lunaaa Bbby',
                    'Lux',
                    'Lydia Rose',
                    'Lyracr0W0 Vip',
                    'M Thando',
                    'M Winter',
                    'Macy Sadler',
                    'Maddison Rose',
                    'Madeline',
                    'Madi Xo',
                    'Mae',
                    'Mae Onlyfans888',
                    'Mag Oos',
                    'Maggie',
                    'Maggie May',
                    'Magic Mia',
                    'Maidofjade Xo',
                    'Makayla',
                    'Mali Mccarthy',
                    'Mama Bare',
                    'Mamabear 15',
                    'Mancini',
                    'Manda',
                    'Mandy',
                    'Mandz Sgh',
                    'Manic Pixie',
                    'Mari Mari',
                    'Maria Thick',
                    'Mariah',
                    'Mariah Xrg',
                    'Marie Xoxo',
                    'Marielove',
                    'Marilyn Monrose',
                    'Marin Egirl',
                    'Marlen',
                    'Marley',
                    'May Bee',
                    'Mayra Ale',
                    'Mc Rebecca',
                    'Mckenzie',
                    'Meg Mark',
                    'Megan Wild',
                    'Melina Mcr',
                    'Mely Melissa',
                    'Meredith',
                    'Mermaid Mo',
                    'Mia Avalon',
                    'Mian Of',
                    'Michele',
                    'Michigan Mami',
                    'Midwest Gal',
                    'Mikaylah',
                    'Milff Mariee',
                    'Mindi',
                    'Minx',
                    'Mirro 87',
                    'Misaki',
                    'Miss Meringue',
                    'Miss Michelle',
                    'Miss Minaaxo',
                    'Miss Minaaxodeals',
                    'Missd',
                    'Mistress Mac',
                    'Misty',
                    'Misty Diva1',
                    'Mochi',
                    'Monica',
                    'Morena Juice',
                    'Moriah',
                    'Mrmuscle',
                    'Ms Juicybooty',
                    'Ms Sancha',
                    'Ms Sethi',
                    'Mystical Nana',
                    'Nadia',
                    'Nance Do',
                    'Naomi',
                    'Natalee',
                    'Natasha',
                    'Nathan',
                    'Naughty Ivana',
                    'Nayeli',
                    'Neeko',
                    'Nessy',
                    'Nicki The Peach',
                    'Nickii',
                    'Nicole',
                    'Nicole Brooks',
                    'Nicole Curtis',
                    'Nicole Tv',
                    'Nicole Wright',
                    'Nikki',
                    'Nina',
                    'Nina Star Xxx',
                    'Noemie',
                    'Nominal Naomi',
                    'Notur Play Bunny',
                    'Nova',
                    'Nova Nobu',
                    'O Kxxx',
                    'Oc Girl',
                    'Oceane',
                    'Official Mylez',
                    'Oksana',
                    'Olivia Hansen26',
                    'Olivia Love',
                    'Oliviajames 02',
                    'Only Bree',
                    'Only Miaharper',
                    'Onlyfans Nastya',
                    'Oriola Yaya',
                    'Paige Summers',
                    'Panos Greek',
                    'Patricia',
                    'Pau Blaz',
                    'Peach',
                    'Peach Xxxxx',
                    'Peaches',
                    'Peachprincess Free',
                    'Peachy Penny',
                    'Pedro',
                    'Penelope Rose',
                    'Penny Mae',
                    'Pennylane',
                    'Persian Muffins',
                    'Peyton',
                    'Pfp By Lavelis',
                    'Playmate 02',
                    'Pocahontas',
                    'Poema',
                    'Poison Ivy',
                    'Porcelana',
                    'Prettii Denaii',
                    'Princess Jasmine',
                    'Princess Mono Hoe Ke',
                    'Priya',
                    'Queen Brii',
                    'Queen Luna',
                    'Queen Of Joi',
                    'Queen Of Pattaya',
                    'Queen Of Spades',
                    'Rachel Williams',
                    'Railey Dieselimages',
                    'Raindrop',
                    'Raine',
                    'Raquel',
                    'Raven',
                    'Raven Hart',
                    'Raylene',
                    'Rayne',
                    'Rayray',
                    'Re Neko',
                    'Red Rutland',
                    'Reese',
                    'Reina Sofia',
                    'Remi Reyes',
                    'Riley',
                    'Riley Reign',
                    'Riri X',
                    'Riri Ximages',
                    'Rissa',
                    'River',
                    'Rose Anna',
                    'Rosemarie',
                    'Roxy Babyy',
                    'Ruby',
                    'Ruby Dawn',
                    'Ruby Soho',
                    'Rubyred',
                    'Rusty',
                    'Ryan Kaoud',
                    'Rylee',
                    'Sabrina',
                    'Sabrina Skyee',
                    'Sage Nova',
                    'Samantha Ava',
                    'Samara',
                    'Sammi Starfish',
                    'Sammie',
                    'Sammy',
                    'Sandy Neko Chan',
                    'Sandycheeks',
                    'Saniah Xo',
                    'Sansa',
                    'Sara',
                    'Sara Boyd',
                    'Sara Love01',
                    'Sara Rose',
                    'Sara Sky',
                    'Saraaa A222',
                    'Sarah Jay',
                    'Sarah Wi 2002',
                    'Sarebear',
                    'Sasha',
                    'Saturnalia Lee',
                    'Savannah Lee',
                    'Savie',
                    'Scarlet',
                    'Scarlett',
                    'Scarlett Kiss',
                    'Scarlett Rose',
                    'Scarlettrose',
                    'Secretmistress Mallory',
                    'Selena',
                    'Selena Brown',
                    'Selina',
                    'Senpai Kai',
                    'Sera Toni',
                    'Sexy Lexi',
                    'Sexy Lexy',
                    'Sexy Spice',
                    'Sexygirl 1',
                    'Sexythangyang Free',
                    'Shaylynn',
                    'Shayna',
                    'Shelbi',
                    'Shelby',
                    'Shyna Ari',
                    'Sidney',
                    'Sierra',
                    'Simply Sam',
                    'Siren',
                    'Siren Sin',
                    'Sky Fontaine',
                    'Skye',
                    'Skylar',
                    'Skylar Marie',
                    'Skywalker',
                    'Sloanb Free',
                    'Smittenkitten',
                    'Snook',
                    'Snowbunny',
                    'Sofia',
                    'Sofia Sofia',
                    'Sofie',
                    'Sofie Nina',
                    'Sonya',
                    'Soof Huang',
                    'Soph Bunni',
                    'Sophia',
                    'Sophia Bunni',
                    'Sophia Savage Free',
                    'Sophie',
                    'Southern Barbie',
                    'Southern Girl',
                    'Southern Sweetness',
                    'Spanishmami',
                    'Spicy Redheadd',
                    'Squirt Goddess',
                    'Stacy',
                    'Stefany Diaz 21',
                    'Steph',
                    'Stephanie',
                    'Strawberii Milk',
                    'Strawberry',
                    'Subby Bunny',
                    'Such A Sweetheart',
                    'Sum Buttcheeks',
                    'Sumbaby2 0',
                    'Summer Brookes',
                    'Sunshine Babe',
                    'Sunshine Xo',
                    'Swang',
                    'Sweetcheeks',
                    'Sweetest Peach',
                    'Sweetpeach 95',
                    'Switch Pixie',
                    'Sylvia',
                    'T Bonez',
                    'T Candy',
                    'Talyn',
                    'Tanaka Kawano',
                    'Tanya Kitsune',
                    'Tasha',
                    'Taste Kimtiddies',
                    'Taste Of Heaven',
                    'Tasty Cinnamon',
                    'Taylor Jx',
                    'Taylor Mae',
                    'Taylor Marie',
                    'Taylor Marieimages',
                    'Taylored',
                    'Tenshi Oh',
                    'Terra',
                    'Tessa',
                    'Thats So Rae',
                    'The Greatest10',
                    'The Milk Man',
                    'Throat Goat',
                    'Tia Maria',
                    'Tianna',
                    'Tiffanies Toes',
                    'Tiffany 1993',
                    'Tiger Queen',
                    'Tilly',
                    'Tina 420',
                    'Tina Diaz',
                    'Tokyo Yoshika',
                    'Tomi King',
                    'Tootie',
                    'Trinity',
                    'Trixie Belle',
                    'Trixie Steele',
                    'Ts Melanie',
                    'Tsuki Neko',
                    'Tyler James',
                    'U Inkuru',
                    'U Lucyuwu',
                    'Unknown Blondie',
                    'V Boudoir',
                    'Valentina Lavida',
                    'Valkyrie Freya',
                    'Vanessa Liberte',
                    'Vanessa Marie',
                    'Vanna',
                    'Venus',
                    'Veronica',
                    'Vickki Ts',
                    'Victoria',
                    'Victoria Grace',
                    'Victoria Kennedy',
                    'Victoria Peach',
                    'Victoria Rose',
                    'Victoria Vixen',
                    'Viking Goddess',
                    'Viky Sxy',
                    'Violet Sky',
                    'Violett Rose',
                    'Violetta',
                    'Vivian',
                    'Vod K',
                    'Vvs Diamonds',
                    'Wetkitty',
                    'Whitney Mae',
                    'Wifey',
                    'Willow Deean',
                    'Winnie',
                    'X Xpeachy',
                    'Xbabylu Premium',
                    'Xo Mic',
                    'Xxx K',
                    'Ya Stacey',
                    'Yami Tv',
                    'Ybn Zell',
                    'Yomomma Com',
                    'Young Gill',
                    'Yourdreamgirl',
                    'Yourdreamgirl2 0',
                    'Yumi Kiwi',
                    'Z Annemarie',
                    'Zelda',
                    'Zinnia',
                ],
            'locations' =>
                [
                    'Abilene',
                    'Abilene Tx',
                    'Aiken',
                    'Aiken Sc',
                    'Akron',
                    'Alabama',
                    'Albany',
                    'Albany Ga',
                    'Albany Ny',
                    'Albuquerque',
                    'Albuquerque Nm',
                    'Allentown',
                    'Allentown Pennsylvania',
                    'Altoona',
                    'Altoona Pa',
                    'Amarillo',
                    'Amarillo Texas',
                    'Amarillo Tx',
                    'Anchorage',
                    'Anchorage Alaska',
                    'Anderson Sc',
                    'Arizona',
                    'Arkansas',
                    'Asheville',
                    'Ashland Ky',
                    'Athens Ga',
                    'Atlanta',
                    'Atx',
                    'Auburn',
                    'Auburn Al',
                    'Augusta',
                    'Augusta Georgia',
                    'Austin',
                    'Austin Texas',
                    'Bakersfield',
                    'Baltimore',
                    'Baltimore Md',
                    'Bangor',
                    'Baton Rouge',
                    'Baton Rouge Louisiana',
                    'Bayarea',
                    'Beckley',
                    'Beckley Wv',
                    'Bellingham',
                    'Bellingham Washington',
                    'Berwick',
                    'Billings Mt Usa',
                    'Binghamton Ny',
                    'Birmingham Al',
                    'Birmingham Alabama',
                    'Bismarck',
                    'Bismarck Nd',
                    'Bloomington In',
                    'Bloomington Indiana',
                    'Boise Idaho',
                    'Bolton',
                    'Boston',
                    'Boston Massachusetts',
                    'Bowling Green Ky',
                    'Bremen',
                    'Bremerton',
                    'Bremerton Washington',
                    'Bronx',
                    'Bronx New York',
                    'Brooklyn',
                    'Brooklyn Ny',
                    'Brownsville',
                    'Brownsville Texas',
                    'Brownsville Tx',
                    'Buffalo',
                    'Buffalo Ny',
                    'Bullhead City Arizona',
                    'Butler',
                    'Cali',
                    'Canada 403',
                    'Canaria',
                    'Canton Ohio',
                    'Cape Cod',
                    'Carson',
                    'Cartagena',
                    'Casper Wy',
                    'Cd Juarez',
                    'Cedar Rapids',
                    'Cedar Rapids Ia',
                    'Central Illinois',
                    'Champaign',
                    'Charleston',
                    'Charleston South Carolina',
                    'Charleston Wv',
                    'Charlotte Nc',
                    'Chatsworth',
                    'Chattanooga Tn',
                    'Cheyenne Wyoming',
                    'Chicago',
                    'Chillicothe Ohio',
                    'Cincinnati',
                    'Ciudad Juarez',
                    'Clarksville',
                    'Clarksville Tn',
                    'Cleveland',
                    'Coeur D Alene Idaho',
                    'College Station',
                    'Colorado Springs',
                    'Colorado Springs Co',
                    'Colorado Springs Colorado',
                    'Columbia Missouri',
                    'Columbia Sc',
                    'Columbia South Carolina',
                    'Columbus',
                    'Columbus Ga',
                    'Columbus Indiana',
                    'Connecticut',
                    'Cookeville',
                    'Cookeville Tn',
                    'Corpus',
                    'Cortland Ny',
                    'Crawfordsville',
                    'Cumberland Md',
                    'Cumming',
                    'Dallas',
                    'Dallas Texas',
                    'Dalton Georgia',
                    'Danville',
                    'Davenport Iowa',
                    'Dayton',
                    'Dayton Ohio',
                    'Daytona Beach',
                    'Daytona Beach Fl',
                    'Decatur',
                    'Defiance Oh',
                    'Delaware',
                    'Delco',
                    'Denver',
                    'Denver Co',
                    'Des Moines Ia',
                    'Des Moines Iowa',
                    'Dubai',
                    'Dubuque Ia',
                    'Duluth',
                    'East Tennessee',
                    'East Texas',
                    'Eastern Kentucky',
                    'Eau Claire',
                    'El Paso Texas',
                    'El Paso Tx',
                    'Elkhart',
                    'Elmira',
                    'Elmira Ny',
                    'Erie Pa',
                    'Eugene',
                    'Eugene Oregon',
                    'Evansville',
                    'Evansville In',
                    'Fall River Mass',
                    'Fargo',
                    'Farmington',
                    'Fayetteville',
                    'Felton',
                    'Findlay Oh',
                    'Florence Ky',
                    'Florianopolis Santa Catarina',
                    'Fort Lauderdale',
                    'Fort Myers Fl',
                    'Fort Myers Florida',
                    'Fort Wayne',
                    'Fort Worth Tx',
                    'Fredericksburg',
                    'Fresno',
                    'Fresno Ca',
                    'Gainesville',
                    'Gainesville Fl',
                    'Gainesville Florida',
                    'Geneve',
                    'Georgia',
                    'Gilbert Arizona',
                    'Gillette',
                    'Granby',
                    'Grand Forks',
                    'Grand Junction',
                    'Grand Junction Colorado',
                    'Grand Rapids Mi',
                    'Grand Rapids Michigan',
                    'Great Falls',
                    'Great Falls Montana',
                    'Green Bay',
                    'Greensboro',
                    'Greensboro Nc',
                    'Greenville',
                    'Greenville Nc',
                    'Greenville Sc',
                    'Guam',
                    'Guanajuato',
                    'Guatemala City',
                    'Hamilton Oh',
                    'Hamilton Ohio',
                    'Harlingen',
                    'Harrisburg',
                    'Hawaii',
                    'Hell\'s Kitchen',
                    'Henderson',
                    'Hertfordshire',
                    'Hickory Nc',
                    'Honolulu',
                    'Houston',
                    'Houston Tx',
                    'Humboldt',
                    'Huntington',
                    'Huntington Wv',
                    'Huntsville Al',
                    'Huntsville Alabama',
                    'I Live In Columbus Indiana',
                    'Idaho',
                    'Idaho Falls Idaho',
                    'Illinois',
                    'Indiana',
                    'Indianapolis',
                    'Indianapolis In',
                    'Indio',
                    'Iowa',
                    'Islas Canarias',
                    'Jackson Mi',
                    'Jackson Tennessee',
                    'Jackson Tn',
                    'Jacksonville Fl',
                    'Jacksonville Nc',
                    'Jamestown',
                    'Jersey',
                    'Jersey Shore',
                    'Johnson City Tn',
                    'Johnstown Pa',
                    'Joliet Il',
                    'Joliet Illinois',
                    'Joplin',
                    'Juneau Ak',
                    'Kalamazoo',
                    'Kansas',
                    'Kansas City',
                    'Katy Tx',
                    'Kauai',
                    'Keene Nh',
                    'Kenosha',
                    'Kentucky',
                    'Kerrville',
                    'Kerrville Tx',
                    'Killeen Texas',
                    'Killeen Tx',
                    'Kingsport Tn',
                    'Kingsville',
                    'Knoxville',
                    'Kokomo',
                    'Lafayette Indiana',
                    'Lafayette Louisiana',
                    'Lake Charles',
                    'Lakeland',
                    'Lakeland Fl',
                    'Lancaster',
                    'Lancaster Ohio',
                    'Lancaster Pa',
                    'Lansing',
                    'Lansing Michigan',
                    'Laredo Texas',
                    'Laredo Tx',
                    'Las Cruces',
                    'Las Cruces New Mexico',
                    'Las Vegas',
                    'Laurel',
                    'Lawton',
                    'Lawton Oklahoma',
                    'Lebanon',
                    'Lewiston',
                    'Lewiston Maine',
                    'Lexington Kentucky',
                    'Lexington Ky',
                    'Lima Ohio',
                    'Lincoln Ne',
                    'Lincoln Nebraska',
                    'Little Rock Arkansas',
                    'Lock Haven',
                    'Lock Haven Pa',
                    'Logan',
                    'London Ky',
                    'Long Island Ny',
                    'Longisland',
                    'Longview',
                    'Longview Tx',
                    'Longview Wa',
                    'Louisiana',
                    'Louisville',
                    'Louisville Ky',
                    'Lowell',
                    'Lowell Ma',
                    'Lubbock',
                    'Lynchburg',
                    'Macon',
                    'Madison',
                    'Madison Wi',
                    'Madison Wisconsin',
                    'Maine',
                    'Malibu',
                    'Manchester Nh',
                    'Mansfield',
                    'Mansfield Ohio',
                    'Marietta',
                    'Marion',
                    'Marion Ohio',
                    'Marquette',
                    'Maryland',
                    'Massachusetts',
                    'Maui Hawaii',
                    'Maui Hi',
                    'Mcallen',
                    'Mcallen Texas',
                    'Medellin',
                    'Medellin Colombia',
                    'Medford',
                    'Medford Or',
                    'Melbourne Australia',
                    'Melrose',
                    'Memphis',
                    'Memphis Tn',
                    'Merced',
                    'Merced Ca',
                    'Mexicali',
                    'Mexicali Baja California Mexico',
                    'Mexicali Bc',
                    'Mexico',
                    'Mexico City',
                    'Michigan',
                    'Midland Tx',
                    'Midwest',
                    'Milwaukee',
                    'Minneapolis',
                    'Minnesota',
                    'Mississippi',
                    'Missouri',
                    'Missouri Usa',
                    'Mn',
                    'Mobile Alabama',
                    'Modesto',
                    'Modesto California',
                    'Monroe Louisiana',
                    'Montana',
                    'Monterrey',
                    'Monterrey Nuevo Leon',
                    'Morgantown',
                    'Morristown',
                    'Mount Vernon Wa',
                    'Muncie Indiana',
                    'Muskegon',
                    'Muskogee',
                    'Myrtle Beach',
                    'Myrtle Beach Sc',
                    'Nagoya',
                    'Nanaimo',
                    'Naples Florida',
                    'Nashville',
                    'Nashville Tn',
                    'Nebraska',
                    'Nepa',
                    'New Bedford Ma',
                    'New Haven Ct',
                    'New Jersey',
                    'New Mexico',
                    'New Orleans',
                    'New Orleans Louisiana',
                    'New York Nyc',
                    'Newark',
                    'Nj',
                    'Nky',
                    'Nola',
                    'North Carolina',
                    'North Carolina Usa',
                    'North Dakota',
                    'North West Uk',
                    'Northern California',
                    'Northern Michigan',
                    'Northern Va',
                    'Nw Indiana',
                    'Nwi',
                    'Nyc Nj Fl',
                    'Oahu Hawaii',
                    'Ocala Fl',
                    'Ocala Florida',
                    'Odessa',
                    'Odessa Tx',
                    'Ohio',
                    'Okc',
                    'Oklahoma',
                    'Omaha',
                    'Omaha Ne',
                    'Oregon',
                    'Orlando',
                    'Orlando Fl',
                    'Oswego',
                    'Owensboro',
                    'Oxnard',
                    'Pacific Northwest',
                    'Paducah Kentucky',
                    'Palm Beach Fl',
                    'Palm Springs',
                    'Palm Springs California',
                    'Palmdale',
                    'Panama City',
                    'Panama City Beach Fl',
                    'Parkersburg Wv',
                    'Penn State',
                    'Pennsylvania',
                    'Pennsylvania Usa',
                    'Pensacola Fl',
                    'Pensacola Florida',
                    'Peoria',
                    'Peoria Il',
                    'Perkins',
                    'Philadelphia',
                    'Philly',
                    'Phoenix',
                    'Phoenix Az',
                    'Piqua',
                    'Pittsburgh',
                    'Plymouth',
                    'Port Angeles Wa',
                    'Port Hope Ontario',
                    'Port Huron Mi',
                    'Port Saint Lucie',
                    'Port St Lucie',
                    'Portland',
                    'Portland Or',
                    'Portsmouth',
                    'Providence Ri',
                    'Pueblo Colorado',
                    'Quad Cities Iowa And Illinois',
                    'Queens Nyc',
                    'Quincy',
                    'Quincy Illinois',
                    'Radford',
                    'Raleigh',
                    'Raleigh North Carolina',
                    'Rapid City Sd',
                    'Reading Pa',
                    'Redding Ca',
                    'Redding California',
                    'Reno Nevada',
                    'Reno Nv',
                    'Rgv Tx',
                    'Rhode Island',
                    'Richmond',
                    'Richmond Ky',
                    'Richmond Va',
                    'Roanoke',
                    'Roanoke Va',
                    'Rochester',
                    'Rochester Mn',
                    'Rochester Ny',
                    'Rockford',
                    'Rockford Il Usa',
                    'Roma Lazio',
                    'Rome Ga',
                    'Rome Georgia',
                    'Roseburg Or',
                    'Roswell',
                    'Roswell New Mexico',
                    'Rva',
                    'Sacramento',
                    'Saint Augustine Florida',
                    'Salem Oregon',
                    'Salinas',
                    'Salinas Ca',
                    'Salt Lake City',
                    'Salt Lake City Ut',
                    'San Angelo',
                    'San Angelo Texas',
                    'San Antonio',
                    'San Antonio Tx',
                    'San Bernardino',
                    'San Bernardino California',
                    'San Diego',
                    'San Diego California',
                    'San Jose',
                    'San Jose Ca',
                    'San Pornando Valley Ca',
                    'Sandpoint Idaho',
                    'Santa Barbara',
                    'Santa Clarita',
                    'Santa Cruz',
                    'Santa Rosa',
                    'Santander',
                    'Sarasota',
                    'Savannah',
                    'Savannah Ga',
                    'Savannah Georgia',
                    'Scranton',
                    'Seattle',
                    'Shawnee',
                    'Sheboygan So',
                    'Shreveport',
                    'Sioux City Ia',
                    'Sioux Falls Sd',
                    'Slo Ca',
                    'Somerset',
                    'Somerville',
                    'South Carolina',
                    'South Dakota',
                    'South Georgia',
                    'South Texas',
                    'Southern Illinois',
                    'Southern New Jersey',
                    'Southwest Virginia',
                    'Spokane',
                    'Spokane Wa',
                    'Springfield Il',
                    'Springfield Illinois',
                    'Springfield Ma',
                    'Springfield Missouri',
                    'Springfield Mo',
                    'Springfield Ohio Columbus Ohio',
                    'St Louis',
                    'St Louis Mo',
                    'Staten Island New York',
                    'Staten Island Ny',
                    'Stockton Ca',
                    'Sydney',
                    'Sydney Australia',
                    'Syracuse',
                    'Syracuse Ny',
                    'Tacoma',
                    'Tacoma Washington',
                    'Taiga',
                    'Tallahassee',
                    'Tallahassee Florida',
                    'Tampa',
                    'Tampa Fl',
                    'Tennessee',
                    'Tennessee Chattanooga',
                    'Tennessee Usa',
                    'Terre Haute In',
                    'Texarkana',
                    'Texas',
                    'Thailand Pattaya',
                    'The Bay Area California',
                    'Tijuana',
                    'Tokyo',
                    'Toledo',
                    'Toledo Ohio',
                    'Topeka',
                    'Torrington',
                    'Traverse City',
                    'Tri Cities Washington',
                    'Tucson',
                    'Tucson Arizona',
                    'Tulsa',
                    'Tuscaloosa',
                    'Tyler Texas',
                    'United States',
                    'Upper Michigan',
                    'Upstate',
                    'Upstate Ny',
                    'Va 757',
                    'Vancouver Wa',
                    'Vermont',
                    'Villavicencio',
                    'Virginia',
                    'Virginia Beach',
                    'Visalia',
                    'Waco',
                    'Waco Tx',
                    'Warner',
                    'Warner Robins',
                    'Warner Robins Ga',
                    'Warren Pa',
                    'Washington Dc',
                    'Washington State',
                    'Wasilla Ak',
                    'Waterloo Iowa',
                    'Watertown',
                    'Waukegan Il',
                    'West Monroe La',
                    'West Palm Beach',
                    'West Virginia Usa',
                    'Wichita',
                    'Wichita Falls',
                    'Wichita Falls Texas',
                    'Wichita Kansas',
                    'Williamsport Pa',
                    'Wilmington Nc',
                    'Winston Salem Nc',
                    'Wisco',
                    'Wisconsin',
                    'Woodland',
                    'Worcester',
                    'Wv',
                    'Wyoming',
                    'Yakima',
                    'York Pa',
                    'Youngstown Ohio',
                    'Yuba City',
                    'Yuma Arizona',
                    'Yuma Az',
                    'Yuma Azimages',
                    'Zanesville Ohio',
                    'Zurich',
                ],
            'ethnicity' =>
                [
                    'Ae Thai',
                    'African',
                    'Alaskan',
                    'Albania',
                    'Albanian',
                    'Arab Ts',
                    'Argentina',
                    'Armenian',
                    'Asian',
                    'Asian Good Girl',
                    'Australia',
                    'Belgium',
                    'Bengali',
                    'Black',
                    'Blackgirl',
                    'Bolivia',
                    'Brazil',
                    'British Twinks',
                    'Bulgaria',
                    'Cambodia',
                    'Canada',
                    'Caribbean',
                    'Catracha',
                    'Central African Republic',
                    'Chile',
                    'Chinese',
                    'Chola',
                    'Colombia',
                    'Costa Rica',
                    'Croatia',
                    'Cuba',
                    'Czech Republic',
                    'Danish',
                    'Denmark',
                    'Dominican Republic',
                    'Dominicana',
                    'Ebony',
                    'Ebony Onlyfans',
                    'Ecuador',
                    'El Salvador',
                    'England Uk',
                    'Filipina',
                    'Filipino',
                    'France',
                    'Free Asian',
                    'Germany',
                    'Greece',
                    'Gringa',
                    'Guatemala',
                    'Haiti',
                    'Hmong',
                    'Honduras',
                    'Hrvatska',
                    'India',
                    'Indian',
                    'Indonesia',
                    'Indonesian',
                    'Iraqi',
                    'Ireland',
                    'Islander',
                    'Israel',
                    'Italian',
                    'Italy',
                    'Jamaica',
                    'Jamaican',
                    'Japan',
                    'Japanese',
                    'Jewish Princess',
                    'Korean',
                    'Latina',
                    'Latina Madura',
                    'Latina Milf',
                    'Latinas',
                    'Latino',
                    'Lebanese',
                    'Malaysia',
                    'Malaysian',
                    'Mexican',
                    'Mexicana',
                    'Morena',
                    'Moroccan',
                    'Morocco',
                    'Muslim',
                    'Native',
                    'Navajo',
                    'Nepal',
                    'Netherlands',
                    'Nicaragua',
                    'Nigeria',
                    'Norway',
                    'Norwegian',
                    'Pakistan',
                    'Pakistani',
                    'Palestine',
                    'Panama',
                    'Paraguay',
                    'Persian',
                    'Peru',
                    'Peruvian',
                    'Philippines',
                    'Pinay',
                    'Poland',
                    'Polish',
                    'Polynesian',
                    'Portugal',
                    'Puerto Rico',
                    'Punjabi',
                    'Romania',
                    'Russian',
                    'Saudi',
                    'Saudi Arabia',
                    'Scandinavian',
                    'Scotland',
                    'Scottish',
                    'Singapore',
                    'Slovakia',
                    'Somali',
                    'South Africa',
                    'Spanish',
                    'Sweden',
                    'Swedish',
                    'Syria',
                    'Syrian',
                    'Taiwan',
                    'Thaigirl',
                    'Thailand',
                    'Trinidad',
                    'Turkey',
                    'Turkish',
                    'Turkish Girl',
                    'Turkiye',
                    'Ucrania',
                    'Ukraine',
                    'United Arab Emirates',
                    'Venezuela',
                    'Vietnam',
                    'Vietnamese',
                ],
            'body_attributes' =>
                [
                    'Amputee',
                    'Big Ass',
                    'Big Tits',
                    'Big Titty Goth Gf',
                    'Big Titty Tina',
                    'Bodybuilding',
                    'Brownskin',
                    'Busty',
                    'Butthole',
                    'Feet',
                    'Freckled',
                    'Glasses',
                    'Green Eyed',
                    'Hairy',
                    'Lactating',
                    'Lightskin',
                    'Muscle',
                    'Nipple',
                    'Perky',
                    'Perky Asian',
                    'Small',
                    'Tattoo Milf',
                    'Tattoos',
                    'Throat',
                    'Tight Pussy',
                    'Tiny',
                    'Tongue',
                    'White',
                ],
            'action' =>
                [
                    'Anal',
                    'Backshots',
                    'Blowjob',
                    'Blowjobs',
                    'Bondage',
                    'Doggystyle',
                    'Face Sitting',
                    'Fisting',
                    'Footjob',
                    'Foreplay',
                    'Free Wet Pussy',
                    'Gangbang',
                    'Handjob',
                    'Masturbating',
                    'Orgasm',
                    'Riding',
                    'Spanking',
                    'Squirt Anal Deepthroat',
                    'Squirting',
                    'Squirting Pussy',
                    'Twerk',
                    'Vibrator',
                    'Waxing',
                ],
            'body_type' =>
                [
                    'Athletoes Free',
                    'Bbw',
                    'Bbw Mom',
                    'Bbw Mom Free',
                    'Chubby',
                    'Chubby Milf',
                    'Curly And Curvy',
                    'Curvy Girl',
                    'Curvy Mommy',
                    'Fit Blonde',
                    'Fit Hotwife',
                    'Fit Miley',
                    'Fitnessmodel',
                    'Free Bbw',
                    'Free Curvy Mombod',
                    'Gordita',
                    'Mature Hairy',
                    'Mature Milf Free',
                    'Mature Mom',
                    'Milf',
                    'Milf And Gilf',
                    'Milf Mountain',
                    'Petite',
                    'Pregnant',
                    'Southern Milf',
                    'Ssbbw',
                    'Tallassgirl Free',
                    'Thick',
                    'Thick Latina',
                    'Thickness',
                    'Midget',
                ],
            'orientation' =>
                [
                    'Bisexual',
                    'Gay',
                    'Lesbian',
                ],
            'hair' =>
                [
                    'Blonde',
                    'Blue Hair',
                    'Brunette',
                    'Curly',
                    'Redhead',
                ],
            'gender' =>
                [
                    'Male',
                    'Tgirl',
                    'Trans',
                    'Twinks',
                ],
            'social_network' =>
                [
                    'Tiktok',
                    'Tiktok Stars',
                    'Twitch',
                    'Twitter',
                    'Youtube',
                    'Pornhub',
                    'Reddit',
                    'Skype',
                ],
            'state' => [
                'Alabama', 'Arizona', 'Arkansas', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
                'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
                'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
                'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
                'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
            ],
            'country' => [
                'United States', 'Canada 403', 'Dubai', 'Guam', 'Geneve', 'Guatemala City', 'Hawaii', 'Mexico', 'Mexico City',
                'Melbourne Australia', 'Nagoya', 'Thailand Pattaya', 'United States', 'Zurich'
            ],
            'city' => [
                'Abilene', 'Abilene Tx', 'Aiken', 'Aiken Sc', 'Akron', 'Albany', 'Albany Ga', 'Albany Ny', 'Albuquerque', 'Albuquerque Nm',
                'Allentown', 'Allentown Pennsylvania', 'Altoona', 'Altoona Pa', 'Amarillo', 'Amarillo Texas', 'Amarillo Tx', 'Anchorage',
                'Anchorage Alaska', 'Anderson Sc', 'Asheville', 'Ashland Ky', 'Athens Ga', 'Atlanta', 'Atx', 'Auburn', 'Auburn Al', 'Augusta',
                'Augusta Georgia', 'Austin', 'Austin Texas', 'Bakersfield', 'Baltimore', 'Baltimore Md', 'Bangor', 'Baton Rouge', 'Baton Rouge Louisiana',
                'Bayarea', 'Beckley', 'Beckley Wv', 'Bellingham', 'Bellingham Washington', 'Berwick', 'Billings Mt Usa', 'Binghamton Ny', 'Birmingham Al',
                'Birmingham Alabama', 'Bismarck', 'Bismarck Nd', 'Bloomington In', 'Bloomington Indiana', 'Boise Idaho', 'Bolton', 'Boston',
                'Boston Massachusetts', 'Bowling Green Ky', 'Bremen', 'Bremerton', 'Bremerton Washington', 'Bronx', 'Bronx New York', 'Brooklyn',
                'Brooklyn Ny', 'Brownsville', 'Brownsville Texas', 'Brownsville Tx', 'Buffalo', 'Buffalo Ny', 'Bullhead City Arizona', 'Butler',
                'Cali', 'Canton Ohio', 'Cape Cod', 'Carson', 'Cartagena', 'Casper Wy', 'Cd Juarez', 'Cedar Rapids', 'Cedar Rapids Ia', 'Champaign',
                'Charleston', 'Charleston South Carolina', 'Charleston Wv', 'Charlotte Nc', 'Chatsworth', 'Chattanooga Tn', 'Cheyenne Wyoming',
                'Chicago', 'Chillicothe Ohio', 'Cincinnati', 'Ciudad Juarez', 'Clarksville', 'Clarksville Tn', 'Cleveland', 'Coeur D Alene Idaho',
                'College Station', 'Colorado Springs', 'Colorado Springs Co', 'Colorado Springs Colorado', 'Columbia Missouri', 'Columbia Sc',
                'Columbia South Carolina', 'Columbus', 'Columbus Ga', 'Columbus Indiana', 'Cookeville', 'Cookeville Tn', 'Corpus', 'Cortland Ny',
                'Crawfordsville', 'Cumberland Md', 'Cumming', 'Dallas', 'Dallas Texas', 'Dalton Georgia', 'Danville', 'Davenport Iowa', 'Dayton',
                'Dayton Ohio', 'Daytona Beach', 'Daytona Beach Fl', 'Decatur', 'Defiance Oh', 'Delco', 'Denver', 'Denver Co', 'Des Moines Ia',
                'Des Moines Iowa', 'Dubuque Ia', 'Duluth', 'Eau Claire', 'El Paso Texas', 'El Paso Tx', 'Elkhart', 'Elmira', 'Elmira Ny',
                'Erie Pa', 'Eugene', 'Eugene Oregon', 'Evansville', 'Evansville In', 'Fall River Mass', 'Fargo', 'Farmington', 'Fayetteville',
                'Felton', 'Findlay Oh', 'Florence Ky', 'Florianopolis Santa Catarina', 'Fort Lauderdale', 'Fort Myers Fl', 'Fort Myers Florida',
                'Fort Wayne', 'Fort Worth Tx', 'Fredericksburg', 'Fresno', 'Fresno Ca', 'Gainesville', 'Gainesville Fl', 'Gainesville Florida',
                'Gilbert Arizona', 'Gillette', 'Granby', 'Grand Forks', 'Grand Junction', 'Grand Junction Colorado', 'Grand Rapids Mi',
                'Grand Rapids Michigan', 'Great Falls', 'Great Falls Montana', 'Green Bay', 'Greensboro', 'Greensboro Nc', 'Greenville',
                'Greenville Nc', 'Greenville Sc', 'Hamilton Oh', 'Hamilton Ohio', 'Harlingen', 'Harrisburg', 'Hell\'s Kitchen', 'Henderson',
                'Hertfordshire', 'Hickory Nc', 'Honolulu', 'Houston', 'Houston Tx', 'Humboldt', 'Huntington', 'Huntington Wv', 'Huntsville Al',
                'Huntsville Alabama', 'I Live In Columbus Indiana', 'Idaho Falls Idaho', 'Indianapolis', 'Indianapolis In', 'Indio', 'Jackson Mi',
                'Jackson Tennessee', 'Jackson Tn', 'Jacksonville Fl', 'Jacksonville Nc', 'Jamestown', 'Jersey', 'Jersey Shore', 'Johnson City Tn',
                'Johnstown Pa', 'Joliet Il', 'Joliet Illinois', 'Joplin', 'Juneau Ak', 'Kalamazoo', 'Kansas City', 'Katy Tx', 'Kauai', 'Keene Nh',
                'Kenosha', 'Kerrville', 'Kerrville Tx', 'Killeen Texas', 'Killeen Tx', 'Kingsport Tn', 'Kingsville', 'Knoxville', 'Kokomo',
                'Lafayette Indiana', 'Lafayette Louisiana', 'Lake Charles', 'Lakeland', 'Lakeland Fl', 'Lancaster', 'Lancaster Ohio', 'Lancaster Pa',
                'Lansing', 'Lansing Michigan', 'Laredo Texas', 'Laredo Tx', 'Las Cruces', 'Las Cruces New Mexico', 'Las Vegas', 'Laurel',
                'Lawton', 'Lawton Oklahoma', 'Lewiston', 'Lewiston Maine', 'Lexington Kentucky', 'Lexington Ky', 'Lima Ohio', 'Lincoln Ne',
                'Lincoln Nebraska', 'Little Rock Arkansas', 'Lock Haven', 'Lock Haven Pa', 'Logan', 'London Ky', 'Long Island Ny', 'Longisland',
                'Longview', 'Longview Tx', 'Longview Wa', 'Lowell', 'Lowell Ma', 'Lubbock', 'Lynchburg', 'Macon', 'Madison', 'Madison Wi',
                'Madison Wisconsin', 'Malibu', 'Manchester Nh', 'Mansfield', 'Mansfield Ohio', 'Marietta', 'Marion', 'Marion Ohio', 'Marquette',
                'Maui Hawaii', 'Maui Hi', 'Mcallen', 'Mcallen Texas', 'Medellin', 'Medellin Colombia', 'Medford', 'Medford Or', 'Melrose',
                'Memphis', 'Memphis Tn', 'Merced', 'Merced Ca', 'Mexicali', 'Mexicali Baja California Mexico', 'Mexicali Bc', 'Midland Tx',
                'Milwaukee', 'Minneapolis', 'Modesto', 'Modesto California', 'Monroe Louisiana', 'Monterrey', 'Monterrey Nuevo Leon', 'Morgantown',
                'Morristown', 'Mount Vernon Wa', 'Muncie Indiana', 'Muskegon', 'Muskogee', 'Myrtle Beach', 'Myrtle Beach Sc', 'Nanaimo',
                'Naples Florida', 'Nashville', 'Nashville Tn', 'Nepa', 'New Bedford Ma', 'New Haven Ct', 'New Orleans', 'New Orleans Louisiana',
                'New York Nyc', 'Newark', 'Nola', 'North Carolina', 'North West Uk', 'Northern California', 'Northern Michigan', 'Northern Va',
                'Nw Indiana', 'Nwi', 'Nyc Nj Fl', 'Oahu Hawaii', 'Ocala Fl', 'Ocala Florida', 'Odessa', 'Odessa Tx', 'Orlando', 'Orlando Fl',
                'Oswego', 'Owensboro', 'Oxnard', 'Pacific Northwest', 'Paducah Kentucky', 'Palm Beach Fl', 'Palm Springs', 'Palm Springs California',
                'Palmdale', 'Panama City', 'Panama City Beach Fl', 'Parkersburg Wv', 'Penn State', 'Pensacola Fl', 'Pensacola Florida', 'Peoria',
                'Peoria Il', 'Perkins', 'Philadelphia', 'Philly', 'Phoenix', 'Phoenix Az', 'Piqua', 'Pittsburgh', 'Plymouth', 'Port Angeles Wa',
                'Port Hope Ontario', 'Port Huron Mi', 'Port Saint Lucie', 'Port St Lucie', 'Portland', 'Portland Or', 'Portsmouth', 'Providence Ri',
                'Pueblo Colorado', 'Quad Cities Iowa And Illinois', 'Queens Nyc', 'Quincy', 'Quincy Illinois', 'Radford', 'Raleigh',
                'Raleigh North Carolina', 'Rapid City Sd', 'Reading Pa', 'Redding Ca', 'Redding California', 'Reno Nevada', 'Reno Nv', 'Rgv Tx',
                'Richmond', 'Richmond Ky', 'Richmond Va', 'Roanoke', 'Roanoke Va', 'Rochester', 'Rochester Mn', 'Rochester Ny', 'Rockford',
                'Rockford Il Usa', 'Roma Lazio', 'Rome Ga', 'Rome Georgia', 'Roseburg Or', 'Roswell', 'Roswell New Mexico', 'Rva', 'Sacramento',
                'Saint Augustine Florida', 'Salem Oregon', 'Salinas', 'Salinas Ca', 'Salt Lake City', 'Salt Lake City Ut', 'San Angelo',
                'San Angelo Texas', 'San Antonio', 'San Antonio Tx', 'San Bernardino', 'San Bernardino California', 'San Diego', 'San Diego California',
                'San Jose', 'San Jose Ca', 'San Pornando Valley Ca', 'Sandpoint Idaho', 'Santa Barbara', 'Santa Clarita', 'Santa Cruz',
                'Santa Rosa', 'Santander', 'Sarasota', 'Savannah', 'Savannah Ga', 'Savannah Georgia', 'Scranton', 'Seattle', 'Shawnee',
                'Sheboygan So', 'Shreveport', 'Sioux City Ia', 'Sioux Falls Sd', 'Slo Ca', 'Somerset', 'Somerville', 'South Carolina',
                'South Dakota', 'South Georgia', 'South Texas', 'Southern Illinois', 'Southern New Jersey', 'Southwest Virginia', 'Spokane',
                'Spokane Wa', 'Springfield Il', 'Springfield Illinois', 'Springfield Ma', 'Springfield Missouri', 'Springfield Mo',
                'Springfield Ohio Columbus Ohio', 'St Louis', 'St Louis Mo', 'Staten Island New York', 'Staten Island Ny', 'Stockton Ca',
                'Sydney', 'Sydney Australia', 'Syracuse', 'Syracuse Ny', 'Tacoma', 'Tacoma Washington', 'Tallahassee', 'Tallahassee Florida',
                'Tampa', 'Tampa Fl', 'Tennessee Chattanooga', 'Terre Haute In', 'Texarkana', 'The Bay Area California', 'Tijuana', 'Tokyo',
                'Toledo', 'Toledo Ohio', 'Topeka', 'Torrington', 'Traverse City', 'Tri Cities Washington', 'Tucson', 'Tucson Arizona',
                'Tulsa', 'Tuscaloosa', 'Tyler Texas', 'Upper Michigan', 'Upstate', 'Upstate Ny', 'Va 757', 'Vancouver Wa', 'Villavicencio',
                'Virginia Beach', 'Visalia', 'Waco', 'Waco Tx', 'Warner', 'Warner Robins', 'Warner Robins Ga', 'Warren Pa', 'Washington Dc',
                'Washington State', 'Wasilla Ak', 'Waterloo Iowa', 'Watertown', 'Waukegan Il', 'West Monroe La', 'West Palm Beach', 'Wichita',
                'Wichita Falls', 'Wichita Falls Texas', 'Wichita Kansas', 'Williamsport Pa', 'Wilmington Nc', 'Winston Salem Nc', 'Wisco',
                'Woodland', 'Worcester', 'Wv', 'Yakima', 'York Pa', 'Youngstown Ohio', 'Yuba City', 'Yuma Arizona', 'Yuma Az', 'Yuma Azimages',
                'Zanesville Ohio'
            ],
            'region' => [
                'Central Illinois', 'East Tennessee', 'East Texas', 'Eastern Kentucky', 'Northern California', 'Northern Michigan',
                'Northern Va', 'Pacific Northwest', 'South Carolina', 'South Dakota', 'South Georgia', 'South Texas', 'Southwest Virginia',
                'Southern Illinois', 'Southern New Jersey', 'Va 757'
            ]
        ];
    }
}
